name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: php-actions/composer@v6 # or alternative dependency management
    
    - name: Run Tests
      uses: php-actions/phpunit@v3
      with:
        command: ./vendor/bin/phpunit